// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LinqOptimizer")>]
[<assembly: AssemblyProductAttribute("LinqOptimizer")>]
[<assembly: AssemblyCompanyAttribute("Nessos Information Technologies")>]
[<assembly: AssemblyVersionAttribute("0.7.0")>]
[<assembly: AssemblyFileVersionAttribute("0.7.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LinqOptimizer"
    let [<Literal>] AssemblyProduct = "LinqOptimizer"
    let [<Literal>] AssemblyCompany = "Nessos Information Technologies"
    let [<Literal>] AssemblyVersion = "0.7.0"
    let [<Literal>] AssemblyFileVersion = "0.7.0"
