// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("LinqOptimizer")]
[assembly: AssemblyProductAttribute("LinqOptimizer")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyVersionAttribute("0.6.3")]
[assembly: AssemblyFileVersionAttribute("0.6.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.6.3";
    }
}
